# Generated by Django 3.2.9 on 2021-12-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211220_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='title',
            new_name='name',
        ),
    ]
