# Generated by Django 4.0 on 2021-12-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bikeinstance_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='isbn',
            field=models.CharField(help_text='Bike ID Number</a>', max_length=13, unique=True, verbose_name='Bike ID'),
        ),
    ]
