# Generated by Django 4.0 on 2022-01-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_bikeinstance_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikeinstance',
            old_name='imprint',
            new_name='bike_model',
        ),
    ]
