# Generated by Django 4.0 on 2022-01-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_re_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='re_user',
        ),
    ]
