# Generated by Django 4.0 on 2022-01-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_delete_re_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeinstance',
            name='owner',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
